### ISSUE TITLE
FMF EMR add visible isVisible & setVisible to Script Engine

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#120]
Add possibility to make some widgets visible or invisible  in response to user interaction.

scriptwrappers.h
scriptwrappers.cpp

**Comment by EricMaeker** [comment]
In JavaScript file, use:
- object.ui.hide()
- object.ui.hide()
object.ui gives access to the QWidget class public slots
However, implemented in v1.0
