### ISSUE TITLE
FMF command line version info

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#125]
Tested on Debian only:
freemedforms_debug -v
Utils_debug - 0.9.8 - Debug ; Full application ; Compiled with Qt 5.3.2 - Running with Qt 5.3.2

Utils gets printed instead of FreeMedForms
Same happens for release
Probably a problem with BINARY_NAME definition in config_paths.pri

**Comment by EricMaeker** [comment]
Not a bug, just rebuild everything from scratch.
