### ISSUE TITLE
FMF EMR 0.9.8 grouped exclusive checkboxes remain checked in new episode

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#143]
In a form with a ui file using QButtonGroup for exclusive checkboxes:
Let's say we have two checkboxes, "yes" and "no", grouped together in Creator Designer mode with QButtonGroup set to the default "exclusive".
1. In the current episode, check the "yes" checkbox
2. Add a new episode
3. The checkbox is already checked in the new episode. It should be unchecked.

The reason why I am using exclusive checkboxes instead of radio buttons is that it allow me to use Designer signal and slot mechanism to control other widget without writing dozens of lines of boilerplate & error-prone JavaScript code.

**Comment by EricMaeker** [comment]
Wrong form coding. Please provide you XML form and UI
