### ISSUE TITLE
eDRC doesn't compile: undefined reference edrccore.cpp

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#17]
FMF 0.9.4 master
default debug build (using build.sh)
(without eDRC plugin enabled: no problem)
with eDRC plugin enabled:
Compilation error

log:

Project MESSAGE: Building debug mode without installation
../../build/Qt4_linux-gpp-64/FreeMedForms/eDRC_debug/.obj/unix/edrccore.o: In function `eDRC::EdrcCore::currentDatabaseVersion() const':
/home/elkcloner/fmf/plugins/edrcplugin/edrccore.cpp:153: undefined reference to `eDRC::Internal::DrcDatabase::version() const'
../../build/Qt4_linux-gpp-64/FreeMedForms/eDRC_debug/.obj/unix/consultresult.o: In function `eDRC::Internal::ConsultResult::toHtml(QString const&, QString const&, eDRC::Internal::DrcDatabase&) const':
/home/elkcloner/fmf/plugins/edrcplugin/consultresult.cpp:581: undefined reference to `eDRC::Internal::DrcDatabase::version() const'
collect2: error: ld returned 1 exit status
make[2]: *** [../../bin/freemedforms_Qt4_linux-gpp-64/plugins/libeDRC_debug.so] Erreur 1
make[1]: *** [sub-------plugins-edrcplugin-make_default] Erreur 2
make: *** [sub-plugins-make_default-ordered] Erreur 2

Thanks.

**Comment by EricMaeker** [comment]
fixed
