### ISSUE TITLE
FMF EMR: print preview not optimal

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#171]
print preview is extremely small
temporary fix: adapt QLabel height to parent window heigh (90%), then set width to respect A4 ration

TODO:
- rewrite all printerplugin to use Qt's printdialog (long fix)
  or
- subclass QLabel so that it respects initial ratio: http://stackoverflow.com/questions/5653114/display-image-in-qt-to-fit-label-size (quick fix)

**Comment by EricMaeker** [comment]
New code reverted as it contains many errors and corrected. 

-> Now the preview automatically updates when the dialog is resized by the user.
