### ISSUE TITLE
fsp/fsp.cpp:152: suspicious if sequence

### ISSUE THREAD

**Issue by dcb314** [FreeMedForms/freemedforms#172]
fsp/fsp.cpp:152]: (style) Expression is always false because 'else if' condition matches previous condition at line 150.

Source code is

            if (xmlTag.compare("b.nb", Qt::CaseInsensitive) == 0) {
                return Fsp::Bill_Number;
            } else if (xmlTag.compare("b.nb", Qt::CaseInsensitive) == 0) {
                return Fsp::Bill_Date;
            }

**Comment by EricMaeker** [comment]
Closed with next commit, thanks for reporting
