### ISSUE TITLE
startup login dialog: lineeditechoswitcher widget not useful for login

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#23]
Toggling "login" (aka user name) between hidden and not hidden is not useful.
Suggestion:

libs/utils/widgets/loginwidget.ui
switching corresponding class from Utils::LineEditEchoSwitcher to QLineEdit

libs/utils/widgets/loginwidget.cpp
removing
54  ui->login->setIcon(QIcon(fullAbsPath));

**Comment by jeromecc** [comment]
Fixed in c4afbefcc1b9f80dccb31060f9e83daa63133603

**Comment by EricMaeker** [comment]
Le 13/01/2015 23:52, jeromecc a écrit :
> Toggling "login" (aka user name) between hidden and not hidden is not
> useful.

This was asked by users a long time ago...
There are no problem to keep login & password visibility toggling, this
is absolutely not annoying for users who do not want this feature.

-- 
Eric

**Comment by jeromecc** [comment]
On 14/01/2015 11:55, EricMaeker wrote:
> Le 13/01/2015 23:52, jeromecc a écrit :
> > Toggling "login" (aka user name) between hidden and not hidden is not
> > useful.
>
> This was asked by users a long time ago...
Ok then if it was asked by users, I should reverse the commit.
>
> There are no problem to keep login & password visibility toggling, this
> is absolutely not annoying for users who do not want this feature.
Indeed.
It seemed a bit odd but if some users think it's important, let it be. :-)

**Comment by jeromecc** [comment]
Commit c4afbefcc1b9f80dccb31060f9e83daa63133603 reverted.
