### ISSUE TITLE
In forms' items of type "helptext", tooltip doesn't work

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#25]
In form "SOAP with biometrics", tooltip text doesn't show up when pointer is over helptext items such as:
pulse pressure or BP (mmHg)
Expected behaviour: when pointer is over helptext "BP (mmHg)", we should see tooltip text "Blood Pressure (mmHg)".
Actual behaviour: no tooltip text

See global_resources/forms/subforms/generic/soap_with_biomeasurements/central.xml

**Comment by EricMaeker** [comment]
Done v1.0
