### ISSUE TITLE
FMF EMR segfaults because of errors in forms Qt Ui Linkage

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#26]
FMF Version: master
OS: Debian Stable

After FMF startup, trying to add a subform with errors in QtUiLinkage (<uilink /> in central.xml pointing to non existent element in form.ui file) leads to segfault.

"BaseGroup                 ** ERROR(baseformwidgets.cpp:627) ** Using the QtUiLinkage, item
                          not found in the ui: Subs::Tools::Pediatrics::WithBio:
                          :SubjectiveGroup"

Could we find a way to protect FMF EMR from segfaulting and crashing because of malformed forms?

**Comment by EricMaeker** [comment]
> "BaseGroup ** ERROR(baseformwidgets.cpp:627) ** Using the QtUiLinkage, item
> not found in the ui: Subs::Tools::Pediatrics::WithBio:
> :SubjectiveGroup"

I can not reproduce this bug.
Here is the following test I've done:
- edit global_resources/forms/subforms/fortestonly/ui-test/central.xml
- line 36: change the widget name
- run FMF

-> You have the log on the console
"BaseGroup                 ** ERROR(baseformwidgets.cpp:627) ** Using
the QtUiLinkage, item
                          not found in the ui:
Test::Ui::FirstTest::GroupTest"
"BaseGroup                 ** ERROR(baseformwidgets.cpp:627) ** Using
the QtUiLinkage, item
                          not found in the ui:
Test::Ui::FirstTest::GroupTest"

But no segfault.

Send me your malformated xml file please

-- 
Eric

**Comment by jeromecc** [comment]
Sure. https://www.jerome.cc/pediatrics.tar (the www matters)
Thanks! :-)

**Comment by EricMaeker** [comment]
Le 23/01/2015 11:34, jeromecc a écrit :
> Sure. https://www.jerome.cc/pediatrics.tar (the www matters)
> Thanks! :-)

It is MeasurementWidget that segfaults.
In order, to correctly create mixed QtUI/FMF_XML files you should:
- firstly define your UI and take care of *objectNames*
- use these objectNames in your *.xml file

Look at your central.xml file. None of the widget name does correspond
to the QtUi file.

For sure, a segfault is never a good choice in app design ;) I'll
patchthe code so that it will not segfault.

Thanks for reporting.

I still really believe that a Meteor.js port will be a faster way to
improve UI/App/functionnalities...
-- 
Eric

**Comment by EricMaeker** [comment]
Issue closed with commit 8d7b70afacfe3e7aa8a3fbeaac4ec4f2dedd4bbc

https://github.com/FreeMedForms/freemedforms/commit/8d7b70afacfe3e7aa8a3fbeaac4ec4f2dedd4bbc

**Comment by jeromecc** [comment]
>It is MeasurementWidget that segfaults.
In order, to correctly create mixed QtUI/FMF_XML files you should:
- firstly define your UI and take care of *objectNames*
- use these objectNames in your *.xml file

>Look at your central.xml file. None of the widget name does correspond
to the QtUi file.

Yes I realized this afterwards. :-)

> For sure, a segfault is never a good choice in app design ;) I'll
patchthe code so that it will not segfault.
I tested the malformed form with the patch: it works perfectly.

>I still really believe that a Meteor.js port will be a faster way to
improve UI/App/functionnalities...
I still believe C++ (developed since 1983, fourth most used programming language in TIOBE index),  Qt (developed since 1995) and MySQL (developed since 1995) are weapons of choice for a stable and long term support medical application. Hospitals, clinics, dispensaries and medical practices information systems need stability. Healthcare workers love stability, most of them are not hardcore hackers. Qt 5.4 was just released, it has impressive new features.

Meteor.js would probably be perfect for open data collaborative tools like FreeDDIManager though. :-)
