### ISSUE TITLE
code BMI script in soap_with_biomeasurements subform

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#27]

**Comment by jeromecc** [comment]
I'm testing BMI calculation with pediatrics form in fortestonly folder but I can't get it to work for now. Help appreciated.

**Comment by jeromecc** [comment]
Made it to work with meters and kilograms here:
https://github.com/maternite/freemedforms/tree/master/forms/subforms/maternity/pediatrics/pediatrics_soap_with_biomeasurements
I have to code conversions in JavaScript, unless It's possible to use patientdata in forms.
Notice the 'double':
weight['valueChanged(double)'].connect(this, computeBMI);               
height['valueChanged(double)'].connect(this, computeBMI);

**Comment by EricMaeker** [comment]
Le 10/05/2015 00:29, jeromecc a écrit :
> Made it to work with meters and kilograms here:
> https://github.com/maternite/freemedforms/tree/master/forms/subforms/maternity/pediatrics/pediatrics_soap_with_biomeasurements
> I have to code conversions in JavaScript, unless It's possible to use
> patientdata in forms.

patientdata are available inside javascript if my memory still works
fine (or I didn't completely finished this code).

But why do you want to access to patientdata within this form and for
the BMI computation.

User should inform weight/height. Script could be
- get value of each height/weight
- convert to meters and kilograms
- compute BMI

PS: Good job with UI signal connection. Can you add some documentation
on the wiki for this please.

Eric

**Comment by jeromecc** [comment]
solved with commit 8d1659c793d13ff14607b7eee95dbd2ad0c9d86e
merged
