### ISSUE TITLE
TypeError in scriptmanager.cpp

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#28]
"Chrono - FormManager      0 ms: onCurrentPatientChanged::load subforms" 
com.freemedforms.generic.soapWithBio Setup UI
Script::Internal::FormItemScriptWrapper(name = "FormItemScriptWrapper")
"                          ** ERROR(scriptmanager.cpp:195) ** uncaught exception at line25
                          :TypeError: Result of expression 'formUi.findchild' [undefined]
                          is not a function."

**Comment by EricMaeker** [comment]
Hum, yes this form is currently only a draft one.

**Comment by EricMaeker** [comment]
It is not currently possible to connect to QSpinBox signal in the JS part using FMF scriptmanager.
We need more C++ code before this form could be activated...

**Comment by jeromecc** [comment]
In fact FMF can do this! :)
Have a look at this functional form: https://github.com/maternite/freemedforms/blob/master/forms/subforms/imaging/ultrasound/trimester2/scripts/xx/trimester2.js
On line 54:
trimester2_fetusNumber['valueChanged(int)'].connect(this, trimester2_hideFetusGroupBox);
where trimester2_fetusNumber is a SpinBox which hides or makes visible GroupBoxes.
