### ISSUE TITLE
Data pack manager bug

### ISSUE THREAD

**Issue by ed0c** [FreeMedForms/freemedforms#32]
HI, 
I've installed the 0.9.4 version of freemedforms in debian Jessie, and when I'm trying to download either the CIM 10 classification  or the french pharmaceutical drug database, i encounter an error. In my terminal , I can see this :

"PackManager               Ajout de freemedforms.certified.icd10.free à la liste de
                          téléchargement de freemedforms.community.free" 
"HttpServerEngine          Clearing proxy" 
HTTP:startDownloadQueue; server # 0 "http://packs.freemedforms.com" "freemedforms.community.free" "0.9.0~beta1" 
Downloading pack "http://packs.freemedforms.com/get-icd10/icd10.zip" 
HTTP: serverFinished  QUrl( "http://packs.freemedforms.com/get-icd10/icd10.zip" )  0 
"HttpServerEngine          Writing pack content to /home/alexandre/.freemedforms/datapacks
                          /tmp/freemedforms.certified.icd10.free/icd10.zip" 
"PackManager               ** ERROR(packmanager.cpp:206) ** Fichier du paquet corrompu (
                          /home/alexandre/.freemedforms/datapacks/tmp/freemedforms
                          .certified.icd10.free/icd10.zip)" 
"Warning Dialog            Fichier du paquet corrompu (/home/alexandre/.freemedforms
                          /datapacks/tmp/freemedforms.certified.icd10.free/icd10.zip)"

And when I try to download it manually, It shows me a page in my browser with "You can not access this server." 
Thanks for the support !

**Comment by jeromecc** [comment]
Thanks for reporting. I am aware of this issue and I will look into it ASAP. I'm currently busy rebuilding FMF for Ubuntu & Windows to fix another problem.

**Comment by jeromecc** [comment]
Issue should be solved now. I made a mistake during the transfer of datapacks from the old server to the new VPS (http://packs.freemedforms.com). The zip files were missing. Sorry about that. Thanks for the report. Please confirm that it works for you now so that I can close the issue. :-)

**Comment by ed0c** [comment]
It's all good for me ! Thanks for the quick answer!
