### ISSUE TITLE
building freemedforms for Windows: make stops because of wrong header path in plugins/xmlioplugin/tests/tst_xmlformname.cpp

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#33]
in file plugins/xmlioplugin/tests/tst_xmlformname.cpp
lines 27 & 28:
#include "xmlioplugin.h"
#include "xmlformname.h"

make (on Windows 7 32 bit with MinGW32-make) result in:
xmlioplugin.h can't be found
xmlforname.h can't be found

shoud be:
```xml
#include "../xmlioplugin.h"
#include "../xmlformname.h"
```
Question to @EricMaeker : why is this make bug not happening in Linux build?

**Comment by jeromecc** [comment]
Fixed in commit 229df569b2bdf2182eb29642d729d0d6c40f4a21

**Comment by EricMaeker** [comment]
Le 19/02/2015 13:26, jeromecc a écrit :
> Fixed in commit 229df56
> <https://github.com/FreeMedForms/freemedforms/commit/229df569b2bdf2182eb29642d729d0d6c40f4a21>

Ok for the fix.
You can use "WITH_TESTS=0" in the qmake command line to avoid building
unit tests.

Eric
