### ISSUE TITLE
compilation warning about zip.c & unzip.c

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#38]
During compilation of FMF release on Debian Stable
zip.c: In function ‘zipOpenNewFileInZip3’:
zip.c:907:28: warning: assignment from incompatible pointer type [enabled by default]
unzip.c: In function ‘unzOpenCurrentFile3’:
unzip.c:1176:24: warning: assignment from incompatible pointer type [enabled by default]

**Comment by EricMaeker** [comment]
Le 25/02/2015 12:56, jeromecc a écrit :
> During compilation of FMF release on Debian Stable
> zip.c: In function ‘zipOpenNewFileInZip3’:
> zip.c:907:28: warning: assignment from incompatible pointer type
> [enabled by default]
> unzip.c: In function ‘unzOpenCurrentFile3’:
> unzip.c:1176:24: warning: assignment from incompatible pointer type
> [enabled by default]

This does not represent any problem. This code is part of the zlib and
should not be compiled within Debian as the binary should link to the
installed zlib1g-dev lib.

Eric
