### ISSUE TITLE
FMF wrongly detects forms update

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#39]
Updating forms systematically is a feature of the debug build.

Problem: even in release build, FMF wrongly detects a form update at each startup, and keeps doing so even if the user lets FMF unnecessarily "update" the unchanged forms.

@EricMaeker, this is the last conspicuous and annoying bug that would be nice to fix before releasing 0.9.6, could you have a quick look?

Thanks! :-)

**Comment by jeromecc** [comment]
from plugins/xmlioplugin/xmlformio.cpp
line 523
```C++
if (fileVersion.versionString() == "test" || fileVersion > dbVersion) {
                // update database
                XmlFormName &form = formName(fileDescription->data(Form::FormIODescription::UuidOrAbsPath).toString(), m_FormNames);
```
FMF will always ask to update if forms version is "test" so I suggest switching from
<version>test</versions>
to
<version>0.9.6</version>

for all source forms.

**Comment by jeromecc** [comment]
fixed in commit 085e5ae53830b3b6d4bc34355a98f9d75ec6e980

**Comment by EricMaeker** [comment]
> switching from
> test
> to
> 0.9.6

Nope. The git should always uses "test" version. If you want to release
a stable binary please prepare the source using the script in

	scripts/sources.sh

And build the binary with this only source. The test version is replaced
by the current version (see buildspecs/projectversion.pri).

Thanks to revert please
Eric

**Comment by jeromecc** [comment]
Ok. Done in ec111455d1242fcb8a464e042a5310b93a876dee

I also set all <fmfv> to test, I double checked that fmfv is not used in the code.

I will test all forms with 0.9.6 and set all <fmfv> to 0.9.6 for the builds (maybe we should add a line in scripts/sources.sh to do that?
Are we ok to say that <fmfv>X.X.X</fmfv> means "this forms has been tested to work with FMF version X.X.X"?
I think having all those different versions scattered in forms for fmfv is rather confusing...

I updated the "Building sources packages" paragraph in build instructions with "To release a new version, update version number in buildspecs/projectversion.pri"

Thanks.

**Comment by EricMaeker** [comment]
> I also set all to test, I double checked that fmfv is not used in the code.

Ok

> I will test all forms with 0.9.6 and set all to 0.9.6 for the builds
> (maybe we should add a line in scripts/sources.sh to do that?
> Are we ok to say that X.X.X means "this forms has been tested to work
> with FMF version X.X.X"?

Nope, <version> is the version number of the form itself. It can be
anything you want using the versioning convention of FreeMedForms (see
website for further information).

<fmfv> is the minimum version of FreeMedForms required to use the form.
For eg, some forms does not use any new widgets since 0.8.0.

> I think having all those different versions scattered in forms for fmfv
> is rather confusing...

Please read docs, I think it is clearly defined. Otherwise we should
write some docs ;)

> I updated the "Building sources packages" paragraph in build
> instructions with "To release a new version, update version number in
> buildspecs/projectversion.pri"

Ok I'll take a look at it.

Thanks
Eric
