### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#40]
#### freemedforms-project package is marked as not reproducible by Debian:
https://reproducible.debian.net/sid/amd64/index_FTBFS.html

#### The cause is related to timestamps from cpp macros:
The C pre-processor macros `__DATE__`, `__TIME__`, and `__TIMESTAMP__` captures the current time, and thus will obviously make a build unreproducible.

#### Why do we want reproducible builds?
tldr; for improved **security**: reproducible packages are harder to tamper, but also for other improvements in the distribution, update and dowload of Debian packages
See Debian wiki for further explanations: https://wiki.debian.org/ReproducibleBuilds/

#### There is a patch:
https://wiki.debian.org/ReproducibleBuilds/TimestampsFromCPPMacros

I'll try to fix this ASAP.

**Comment by EricMaeker** [comment]
Hi

This should be done by source.sh script using sed commands.

Éric

**Comment by EricMaeker** [comment]
Done
