### ISSUE TITLE
Arch Linux build: typo in .pro files prevents compilation with Qt 5

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#48]
According to downstream bug report by Arch Linux user benjarobin (https://forums.archlinux.fr/viewtopic.php?f=13&t=16173) make was complaining about missing PadTools.pluginspec

In files freepad/plugins/padtoolsplugin/padtoolsplugin.pro we have:

OTHER_FILES += Padtools.pluginspec

and in file plugins/padtoolsplugin/padtoolsplugin.pro we have:

OTHER_FILES = Padtools.pluginspec

Renaming all Padtools.pluginspec to PadTools.pluginspec solved the problem.

**Comment by jeromecc** [comment]
Fixed in c22e8ef24530d6d99c2a240e5570f017e7bee8f8

**Comment by jeromecc** [comment]
I think this fix commit is wrong https://github.com/FreeMedForms/freemedforms/commit/c22e8ef24530d6d99c2a240e5570f017e7bee8f8
I garbled the AUR fix and my own fix.
Late night commits... :(

**Comment by jeromecc** [comment]
Fixed in c9e5fc368cec523c145f4899d60c8a40bb79bb3d

**Comment by EricMaeker** [comment]
Nop, this is still wrong. Plugin name/make vars/filename must be the
exact same string (case sensitive).

in *.pro:
...
TARGET = PadTools
...
OTHER_FILES = PadTools.pluginspec

in *.pluginspec
<plugin name="PadTools" version="0.0.1" compatVersion="0.0.1">
...

filename
PadTools.pluginspec

in padtoolsplugin.h
...
    Q_PLUGIN_METADATA(IID "org.freemedforms.FreeMedForms.PadToolsPlugin" FILE "PadTools.json")
...

Like this all will be fine. Do you manage the patch?

Eric

**Comment by jeromecc** [comment]
Yes.

**Comment by jeromecc** [comment]
What is the use of the empty json file?

**Comment by EricMaeker** [comment]
Nop, this is still wrong. Plugin name/make vars/filename must be the
exact same string (case sensitive).

in *.pro:
TARGET = PadTools
OTHER_FILES = PadTools.pluginspec

in *.pluginspec
<plugin name="PadTools" version="0.0.1" compatVersion="0.0.1">

filename
PadTools.pluginspec

Like this all will be fine. Do you manage the patch?

Eric

**Comment by EricMaeker** [comment]
Le 09/06/2015 20:08, jeromecc a écrit :
> What is the use of the empty json file?

This file is autogenerated by Qt qmake. You don't have to create this file.

Eric

**Comment by jeromecc** [comment]
This fix works for me. Does it work on Arch Linux Nicolas @nflqt ?

**Comment by nflqt** [comment]
jeromecc <notifications@github.com> writes:

> This fix works for me. Does it work on Arch Linux Nicolas @nflqt ?

Abstract:
It seems to works. ^^


Config:
- ASUS Eeepc 1000H
- Manjaro 32bit (Distro based on Arch)
- QMake version 3.0
  Using Qt version 5.4.1 in /usr/lib


Way:
0. $ cd ~/…/freemedforms

1. $ git pull

2. $ git log

   (The last commit is:
       commit 297b23d1041c14767ced129c596cd4987019d3ca
       Author: Jerome Pinguet <jerome@jerome.cc>
       Date:   Tue Jun 9 21:24:56 2015 +0300

       Hotfix for issue #48)

3. $ qmake freemedforms.pro -r "CONFIG+=debug debug_without_install"

4. $ make

5. $ ./bin/freemedforms_Qt5_linux-gpp/freemedforms_debug

   A little installation window is lauching.

-- 
Nicolas Floquet
www.pharmanerd.flqt.fr | www.logibaba.flqt.fr | www.librehealthcare.org
5, impasse du bois 61450 La Ferrière-aux-Étangs, Normandie, France
06 32 93 03 51
Mail rédigé et signé avec des logiciels libres
PGP : 8CB0 FE5C 27BB A86E 0B6B  1DEA AB88 CF5B 9200 CDB6

**Comment by jeromecc** [comment]
Great! Thank you for your help. I can close the issue now.
