### ISSUE TITLE
Correctly manage database prefix when using FMF with MySQL

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#53]
Files: global_resources/sql/server_config/config.sql & libs/utils/database.cpp
MySQL users creations (FMF regular users or FMF admins) allow access to any database whose name includes "fmf_"
This could be a security issue on a MySQL server that would host multiple instances belonging to different organizations. One user from an organization could use her credentials to connect to databases belonging to another organization because all would include "fmf_" in their names.
Future releases should include prefix into user privileges, restricting access to only one installation.

**Comment by EricMaeker** [comment]
When using server_config.sql, if user define a database prefix, we are wrong. We need to ask user about database prefix before configuring the server, and add a prefix token inside the script to be replaced with the correct value
