### ISSUE TITLE
FMF EMR: radiology exams "xray" form

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#58]
FMF EMR master
debug build
Network install
Using form subforms/prescriptions/assistant_radiology/central.xml
Adding first item prepends text "undefined" to first item in prescription window.

**Comment by jeromecc** [comment]
Quick fix. Please @EricMaeker could you review it before merge? There must be a more elegant solution but it works... Thank you.

**Comment by EricMaeker** [comment]
Ok good fix

Thanks for your work !
Éric

**Comment by jeromecc** [comment]
Forgot to merge... :-)
