### ISSUE TITLE
On MacOS, printers are not detected

### ISSUE THREAD

**Issue by EricMaeker** [FreeMedForms/freemedforms#61]
Run any app of the suite on MacOS, printers will not be detected during the printing process. 
-> Users can not print

Major bug

**Comment by jeromecc** [comment]
Could you add more details to your bug report please?
On what Mac OS version did you run your tests?
Is the current source code affected?
What were the build parameters?
Did you test on both Qt4 and Qt5?

A simple way to overcome this bug is to export the item to pdf and then print the pdf file.

**Comment by EricMaeker** [comment]
Le 19/05/2015 20:27, jeromecc a écrit :
> Could you add more details to your bug report please?

Run app, there aren't any printer detected, even if there are plugged
printers.

> On what Mac OS version did you run your tests?

10.8

> Is the current source code affected?

0.9.x

> What were the build parameters?

Standard, release mode.

> Did you test on both Qt4 and Qt5?

Qt5.1 and Qt5.2
May be Qt4 as the same issue.

> A simple way to overcome this bug is to export the item to pdf and then
> print the pdf file.

Without any detected printers, FMF apps can not provide any PDF file...
If you want this, we must write some pieces of code using the new Qt5
PDF printer.

Eric

**Comment by jeromecc** [comment]
Could you take care of this issue please? I don't have any Apple Computer at hand, my virtual machine is buggy and I don't have a printer...

**Comment by EricMaeker** [comment]
Le 22/05/2015 01:01, jeromecc a écrit :
> Could you take care of this issue please? I don't have any Apple
> Computer at hand, my virtual machine is buggy and I don't have a printer...

Unfortunately, I can not build and test on Mac OS.
Who can work on this issue?
-- 
Eric

**Comment by jeromecc** [comment]
On 05/22/2015 08:48 AM, Eric MAEKER wrote:
> Le 22/05/2015 01:01, jeromecc a écrit :
> > Could you take care of this issue please? I don't have any Apple
> > Computer at hand, my virtual machine is buggy and I don't have a
> printer...
>
> Unfortunately, I can not build and test on Mac OS.
> Who can work on this issue?
> -- 
> Eric
Then how do you know that this bug exists if you didn't build on Mac OS?

-- 
OpenPGP / GPG key: 0x14B7E62420E51038
I encrypt emails with GPG, Thunderbird & Enigmail.

**Comment by EricMaeker** [comment]
> Then how do you know that this bug exists if you didn't build on Mac OS?

This bug was reported three times with the latest released version of
FreeDiams and FreeMedForms (see sourceforge).

Unfortunately, I can not test the newest FMF code with the latest Qt
release on MacOS. So by default, this issue is not solved and is a major
one on MacOS.

We need an offcial MacOS maintainer and/or tester.
-- 
Eric

**Comment by jeromecc** [comment]
>Without any detected printers, FMF apps can not provide any PDF file...
  >If you want this, we must write some pieces of code using the new Qt5
  >PDF printer.

I'm testing FMF 0.9.6 built with Qt 4.8.7 now and it is able to print pdf files without any printer connected.
![pdf_printing_test_fmf096](https://cloud.githubusercontent.com/assets/6979021/8019900/9b5db95a-0c6e-11e5-93aa-33af1ff2eeea.png)

So we can consider the pdf problem solved in 0.9.6 with Qt 4.8.7
I will test printer detection and usage ASAP.
I will build FMF 0.9.6 with Qt 5.3 ASAP.

I hope we are ok to only use Qt 4.8.x and Qt 5.3.x in all our projects to maintain Debian 8.0 Jessie compatibility. Dealing with two Qt versions is difficult, having more than two would be pure madness. :-)

**Comment by jeromecc** [comment]
I successfully built FMF 0.9.6 with Qt5.3 on Mac OS X but unfortunately printing to pdf files doesn't work. It produces a blank 3 kB document.
I noticed that we are using obsolete QPrinter Class functions so I'll try to work on that.

**Comment by jeromecc** [comment]
Possible cause of printer problem in Qt5:
(from http://wiki.qt.io/Transition_from_Qt_4.x_to_Qt5)

QPrinter Doesn't Work

If your code has the following lines:

#include <QPrinter>
#include <QPrintDialog>

add the following to your project file:

QT += printsupport

Again, sometimes it may not work and you would need to be explicit:

#include <QtPrintSupport/QPrinter>
#include <QtPrintSupport/QPrintDialog>

I will try both.

**Comment by jeromecc** [comment]
Please see edited comment online at https://github.com/FreeMedForms/freemedforms/issues/61 to be able to read full documentation snippet (part of it was erased by github markdown) in previous comment.

**Comment by jeromecc** [comment]
Snippet tested. Works perfectly on Mac OS X Yosemite. 
![screenshot from 2015-06-25 18 37 04](https://cloud.githubusercontent.com/assets/6979021/8358878/8d6e898a-1b6b-11e5-8dc9-ee016a14ad54.png)

Let's work from there to fix latest major bug before 0.9.6 release! :-)

**Comment by EricMaeker** [comment]
Le 25/06/2015 17:54, jeromecc a écrit :
> Snippet tested. Works perfectly on Mac OS X Yosemite.
> screenshot from 2015-06-25 18 37 04
> <https://cloud.githubusercontent.com/assets/6979021/8358878/8d6e898a-1b6b-11e5-8dc9-ee016a14ad54.png>
> 
> Let's work from there to fix latest major bug before 0.9.6 release! :-)

Absolutely, this is a good start. I'll make some check of this piece of
code to see if we miss some initalization somewhere

Eric

**Comment by jeromecc** [comment]
Hello @EricMaeker!
I hope you are having a pleasant and relaxing week-end! The sun shines over Istanbul. It is too hot to go outside so I stay indoors and create new branches:

hotfix-0.9.4-i61

Let's solve this Mac OS X printing problem!

Where should we start?

I don't think the problem is only about recognizing printers because in my tests I am able to print correct pdf files (both with Qt4 and Qt5) on Linux and Windows even if there is no printer connected to the computer, whereas on Mac OS X with Qt5 the pdf files created are 3 Kb in size and fail to open (they are Ok with Qt 4.8)...

Thanks.

**Comment by jeromecc** [comment]
Latest commit 90ceb9d8aad123dee236865a415256edd4d21345 changed setResolution(QPrinter::ScreenResolution) to setResolution(QPrinter::HighResolution) in Printer::toPdf in both plugins/printerplugin/printer.cpp and plugins/printerplugin/documentprinter.cpp
seemed to solve the pdf printing problem for Mac OS X with Qt5! :-)

We have a nice readable 30KB pdf document instead of the usual  3 KB unreadable junk file.

I noticed that a printer that I had set earlier (not connected right now) is in the list of printers. I will test with a real printer ASAP.

We are making progress towards fixing the last release critical bug before 0.9.6! :-)

**Comment by jeromecc** [comment]
Commit 90ceb9d8aad123dee236865a415256edd4d21345 solved the printing issue for both printer recognition and pdf issue.
Pdf creation and printing was tested successfully on Mac OS X Yosemite, Windows 7 32 bit and Debian Jessie with both Qt 4.8 and Qt 5.3
Issue solved.

Thanks.
