### ISSUE TITLE
Forms: label text of "measurement" type item printed twice

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#62]
This bug has been around for a long time and happens on both Qt4 and Qt5 versions.
![soap_label_bug](https://cloud.githubusercontent.com/assets/6979021/7705063/b4bdf7c0-fe4a-11e4-9c53-5e2b64ac3797.png)

In SOAP forms, label text (Height, Weight) is printed twice:
1st time at the correct position in the QLabel widget
2nd time at the top left corner of the BaseFormWidget widget

I tried to remove the tooltip text (which doesn't work by the way) but the bug is still there.

I this screencap I remove the Heigh label in central.xml to make the Weight label appear more clearly, but in the original version both words overlap (Weight and Height printed on top of each other at the top left of the screen).

**Comment by jeromecc** [comment]
@EricMaeker can you review the fix before I close the issue?

**Comment by EricMaeker** [comment]
Fixed.
Eric
