### ISSUE TITLE
FreeMedForms EMR: "library not found for -lQtUiTools" build error on Mac OS X Yosemite

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#63]
I'm building from Master using script/mac/mac_release.sh
Build environment:
Mac OS X Yosemite
Qt 4.8.7 (dmg)
Qt 4.8.7 debug libs (dmg)
xcode latest release
system up to date

Building and compilation starts, the first few plugins compile well but then I get this error:

2 warnings generated.
ld: library not found for -lQtUiTools
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../../bin/freemedforms_Qt4_macx-gpp/plugins/libBaseWidgets.dylib] Error 1
make[1]: *** [sub-------plugins-basewidgetsplugin-make_default] Error 2
make[1]: *** Waiting for unfinished jobs....
2 warnings generated.
make: *** [sub-plugins-make_default-ordered] Error 2
   *** Error: make step wrong ***

Any clue @EricMaeker ?

Thank you. :-)

**Comment by jeromecc** [comment]
Adding this line in baseformwidgets.cpp (after #include <QtUiTools/QUiLoader>):
#include <QtUiTools/QtUiTools>
seems to do the trick.
Probably I should test with the more logical and simple
#include <QtUiTools>
? @EricMaeker 
:-)

**Comment by jeromecc** [comment]
Don't pay attention to earlier comment (now deleted): issue still not solved.

**Comment by EricMaeker** [comment]
The problem is inside   the project file of the basewidget plugin
Did you run qmake properly ?
Éric

**Comment by EricMaeker** [comment]
Le 29/05/2015 20:36, Eric Maeker a écrit :
> The problem is inside   the project file of the basewidget plugin
> Did you run qmake properly ?

As you can see in the basewidgets_dependencies.pri

isEqual(QT_MAJOR_VERSION, 5) {
    QT *= uitools
} else {
    CONFIG *= uitools
}

Please, try this:
- correctly **clean** your local working path (see doc or build.sh -h,
don't forget .qmake.cache files)
- ensure qmake is the Qt4 version using qmake -v
- run qmake(-qt4) [...]
- run make -j4

Eric

**Comment by jeromecc** [comment]
As stated in my bug report, I used the mac_release.sh  script.
 Qt4.8.7 is the only Qt version installed on this fresh Yosemite install.

On May 29, 2015 9:44:38 PM EET, Eric MAEKER <notifications@github.com> wrote:
>Le 29/05/2015 20:36, Eric Maeker a écrit :
>> The problem is inside   the project file of the basewidget plugin
>> Did you run qmake properly ?
>
>As you can see in the basewidgets_dependencies.pri
>
>isEqual(QT_MAJOR_VERSION, 5) {
>    QT *= uitools
>} else {
>    CONFIG *= uitools
>}
>
>Please, try this:
>- correctly **clean** your local working path (see doc or build.sh -h,
>don't forget .qmake.cache files)
>- ensure qmake is the Qt4 version using qmake -v
>- run qmake(-qt4) [...]
>- run make -j4
>
>Eric
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/FreeMedForms/freemedforms/issues/63#issuecomment-106900948

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by EricMaeker** [comment]
what is the output of

	qmake -v

Eric

**Comment by jeromecc** [comment]
On 05/29/2015 11:41 PM, Eric MAEKER wrote:
> what is the output of
>
> qmake -v
>
> Eric
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeMedForms/freemedforms/issues/63#issuecomment-106929667>.
>

Mac-mini:~ jerome$ qmake -v
QMake version 2.01a
Using Qt version 4.8.7 in /Library/Frameworks

-- 
OpenPGP / GPG key: 0x14B7E62420E51038
I encrypt emails with GPG, Thunderbird & Enigmail.

**Comment by EricMaeker** [comment]
Ok check existence of the qtuitools dynlib in qt path

Éric

**Comment by EricMaeker** [comment]
>>As you can see in the basewidgets_dependencies.pri
>>
>>isEqual(QT_MAJOR_VERSION, 5) {
>> QT *= uitools
>>} else {
>> CONFIG *= uitools
>>}

May be you should start to build with Qt5.4+ as only the latest Qt is
built on the latest MacOS.

Eric

**Comment by EricMaeker** [comment]
http://download.qt.io/official_releases/qt/5.4/5.4.1/qt-opensource-mac-x64-clang-5.4.1.dmg.mirrorlist

**Comment by jeromecc** [comment]
On 05/30/2015 11:04 AM, Eric MAEKER wrote:
> >>As you can see in the basewidgets_dependencies.pri
> >>
> >>isEqual(QT_MAJOR_VERSION, 5) {
> >> QT *= uitools
> >>} else {
> >> CONFIG *= uitools
> >>}
>
> May be you should start to build with Qt5.4+ as only the latest Qt is
> built on the latest MacOS.
>
> Eric
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeMedForms/freemedforms/issues/63#issuecomment-107006751>.
>
Wrong. :-)
Qt 4.8.7 is built for Mac OS X. I installed it on Yosemite. It works.
Read what Tuuka Turrunen (director of development at Qt) has to say
about it:
http://download.qt.io/official_releases/qt/4.8/4.8.7/qt-opensource-mac-4.8.7.dmg

This new version was specifically released to solve Mac OS X problems..
http://ftp.fau.de/qtproject/official_releases/qt/4.8/4.8.7/changes-4.8.7

 such as pdf:
"- Fix bugs generating PDF on Cocoa [QTBUG-10094]"
Could this bug be related to our problems with printing? It would be
counterproductive not to try with Qt 4.8.7

Moreover, I have to reopen the issue about PMHx because there is indeed
a problem with Qt5. FMF is not Qt5 ready. I want to release a working
app for all platforms soon, it will me much easier to do so with Qt 4.8.7

We haven't tested FMF extensively with Qt5. It would not be reasonable
to release FMF 0.9.6 on Qt5 if it's not tested.

Thanks for your help Eric!

-- 
OpenPGP / GPG key: 0x14B7E62420E51038
I encrypt emails with GPG, Thunderbird & Enigmail.
Please do the same or use my secure contact form: https://jerome.cc/gpg

**Comment by jeromecc** [comment]
Ok check existence of the qtuitools dynlib in qt path

I checked:
I have this in /usr/lib :
libQtUiTools.a
libQtUiTools_debug.a
Is it a naming problem? (lQtUiTools vs libQtUiTools?)
Do I have to add PATH variables in Mac OS X?
I thought this multi billion dollar company closed source OS was a bit more clever than this... :-)

**Comment by jeromecc** [comment]
I opened an issue on Qt for this libQtUiTools linking problem: https://bugreports.qt.io/browse/QTBUG-46439

**Comment by jeromecc** [comment]
It was solved by building Qt 4.8.7 from source by myself.
