### ISSUE TITLE
QPrinter Class: setPageSize(), pageSize() & setNumCopies() are obsolete

### ISSUE THREAD

**Issue by jeromecc** [FreeMedForms/freemedforms#64]
void QPrinter::setPageSize(PageSize newPageSize) should be replaced by void QPrinter::setPaperSize(const QSizeF & paperSize, Unit unit)

PageSize QPrinter::pageSize() const should be replaced by QSizeF QPrinter::paperSize(Unit unit) const

**Comment by jeromecc** [comment]
Working on this on branch hotfix-0.9.4-i64 (FMF 0.9.4 hotfix for issue 64)

**Comment by jeromecc** [comment]
Update: all occurences of QPrinter::pageSize and QPrinter::setPageSize replaced by paperSize() and setPaperSize(): building on Debian is ok. I will test in Windows & MacOS soon, hopefully it will solve issue #61 

setNumCopies() found in
plugins/printerplugin/printdialog.cpp:    m_Printer->printer()->setNumCopies(copies);
plugins/printerplugin/documentprinter.cpp:    printer->setNumCopies(1);
is also obsolete:
void QPrinter::setNumCopies(int numCopies)

Sets the number of copies to be printed to numCopies.

The printer driver reads this setting and prints the specified number of copies.

Use setCopyCount() instead.

I edited the issue title to reflect this.

**Comment by jeromecc** [comment]
Latest update to branch hotfix-0.9.4-i64 is working on Debian with Qt4 & Qt5 but still hasn't solved Mac OS printing issue #61
Let's have a look at this http://www.ics.com/blog/whats-new-qt-53-qprinterinfo as suggested by @EricMaeker  I will test this test code on Mac OS X Yosemite.

**Comment by jeromecc** [comment]
@EricMaeker could you please review this branch before I merge? Thank you! :-)

**Comment by EricMaeker** [comment]
Le 25/06/2015 17:49, jeromecc a écrit :
> @EricMaeker <https://github.com/EricMaeker> could you please review this
> branch before I merge? Thank you! :-)

Please:
- revert: buildspecs/optionalplugins.pri
- update: libs/utils/utils.pro (your code should be in
utils/utils-dependencies.pri instead)

- commit alone: scripts/mac/create_mysql_plugin.sh (nothing to do with
#64), Mac build should be clang not gcc, but whatever.

All other commits looks great. Thanks for the patch.

If you need any help, please ping me.
-- 
Eric
